[project]
name = "biostatistik-und-studiendesign"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyter>=1.1.1",
    "kaleido==0.2.1",
    "numpy>=2.2.2",
    "plotly>=5.24.1",
    "scipy>=1.15.1",
]
